# Generated by Django 4.1 on 2022-08-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('mini_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мини-слоган')),
                ('title', models.TextField(blank=True, max_length=255, null=True, verbose_name='Слоган')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Файсбоок')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Инстаграм')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Востапп')),
                ('gmail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гоогл почта')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Меил почта')),
                ('yandex', models.CharField(blank=True, max_length=255, null=True, verbose_name='Яндекс почта')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Расположение на карте')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Мобильный')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='header_logo', verbose_name='Лого')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Банковские реквизиты')),
                ('bank_recw', models.CharField(blank=True, max_length=255, null=True, verbose_name='Расчетный счет EUR ')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
                'verbose_name_plural': 'Дополнительная информация',
            },
        ),
        migrations.CreateModel(
            name='MainPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Изображение главной страницы ')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Изображение главной страницы ')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Изображение главной страницы ')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Изображение главной страницы ')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Изображение главной страницы ')),
            ],
            options={
                'verbose_name': 'Изображение главной страницы ',
                'verbose_name_plural': 'Изображение главной страницы ',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='ProductContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказы от продукта',
                'verbose_name_plural': 'Заказы от продукта',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='Слайдер')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Слоган')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.BooleanField(default=False, verbose_name='Скидка')),
                ('new', models.BooleanField(default=False, verbose_name='Новый')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган')),
                ('link', models.FileField(blank=True, max_length=254, null=True, upload_to='price_list', verbose_name='Файл для скачки')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Главная изображение')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Второе изображение')),
                ('three_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Третее изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tlo_ru.category', verbose_name='Категория')),
                ('contact_us', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tlo_ru.contactus', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
