# Generated by Django 4.1 on 2022-08-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlo_ru', '0004_remove_product_contact_us_productcontactus_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Изображение'),
        ),
    ]
