# Generated by Django 4.1 on 2022-08-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlo_ru', '0007_contacts_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='bank_recw',
            new_name='bank_recw_eur',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='header_logo',
        ),
        migrations.AddField(
            model_name='contacts',
            name='bank_recw_usd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расчетный счет USD'),
        ),
    ]
