# Generated by Django 4.1 on 2022-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlo_ru', '0008_rename_bank_recw_contacts_bank_recw_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='price_list', verbose_name='Файл для скачки'),
        ),
    ]
