# Generated by Django 4.1 on 2022-08-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlo_ru', '0009_alter_contacts_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='link',
            field=models.FileField(default=1, upload_to='price_list', verbose_name='Файл для скачки'),
            preserve_default=False,
        ),
    ]
