# Generated by Django 4.1 on 2022-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlo_ru', '0010_alter_contacts_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='link',
            field=models.FileField(upload_to='path'),
        ),
    ]
